// Backlog plan for misty-step/cortex.
//
// This file is intended to be consumed by backlog/sync.mjs to create/update:
// - labels
// - milestones
// - issues (including updating existing epic issues #1-#6)
//
// Notes:
// - Issue bodies include a "Backlog-Id: ..." marker for idempotent upserts.
// - Keep bodies Markdown-friendly and context-rich; prefer acceptance criteria.

export const repo = "misty-step/cortex";

const b = (lines) => lines.join("\n");

export const labels = [
  {
    name: "epic",
    color: "5319E7",
    description: "High-level outcome spanning multiple deliverables",
  },
  { name: "area:server", color: "1D76DB", description: "Backend (Hono/Node) work" },
  { name: "area:client", color: "0E8A16", description: "Frontend (React/Vite) work" },
  { name: "area:db", color: "006B75", description: "SQLite/migrations/query work" },
  { name: "area:ci", color: "FBCA04", description: "CI/CD and repo automation" },
  { name: "area:testing", color: "BFDADC", description: "Unit/integration/E2E tests" },
  { name: "area:docs", color: "0075CA", description: "Docs and developer experience" },
  { name: "component:logs", color: "D4C5F9", description: "Logs + errors ingestion, storage, viewing" },
  { name: "component:sse", color: "C5DEF5", description: "Server-Sent Events (real-time updates)" },
  { name: "component:health", color: "F9D0C4", description: "Gateway/agent health collection and UI" },
  { name: "component:sessions", color: "C2E0C6", description: "Sessions collection and UI" },
  { name: "component:sprites", color: "FAD8C7", description: "Sprite fleet status collection and UI" },
  { name: "component:crons", color: "FEF2C0", description: "Cron jobs collection and UI" },
  { name: "component:models", color: "E99695", description: "Model status collection and UI" },
  { name: "component:workspace", color: "D1F2A5", description: "Workspace file browsing and rendering" },
  { name: "component:search", color: "BFD4F2", description: "Search/sort/filter primitives and UX" },
];

export const milestones = [
  {
    title: "Release v0.1 (Logs + Errors)",
    // 2-week target from 2026-02-09; adjust as needed.
    dueOn: "2026-02-22T23:59:59Z",
    description: b([
      "Goal: ship something immediately useful: persisted searchable logs + errors, with a usable UI.",
      "",
      "Scope includes:",
      "- Working DB migrations + server startup wiring",
      "- Log parsers + log-store (FTS) + /api/logs + /api/errors",
      "- Logs/Errors views with search/filter/pagination/export",
      "- (Nice-to-have) SSE live updates",
      "",
      "Non-goals:",
      "- Full OpenClaw CLI collectors beyond what is needed for logs/errors",
    ]),
  },
  {
    title: "Release v0.2 (Health + Agents)",
    dueOn: "2026-03-08T23:59:59Z",
    description: b([
      "Goal: make the dashboard operational for day-to-day monitoring: gateway health + agent status.",
      "",
      "Scope includes:",
      "- OpenClaw integration (CLI runner or HTTP adapter)",
      "- Health collector + /api/health + SSE health events",
      "- Overview health summary + Agent status dashboard (#1)",
    ]),
  },
  {
    title: "Release v0.3 (Ops Views)",
    dueOn: "2026-03-22T23:59:59Z",
    description: b([
      "Goal: complete the remainder of MVP surface area: sessions, sprites, crons, models, workspace browser.",
      "",
      "Scope includes:",
      "- Sessions collector + Sessions view",
      "- Sprite fleet status view (#2)",
      "- Cron job viewer (#3)",
      "- Models view",
      "- Workspace file browser (#4)",
      "- Generalized search/sort/filter (#6) applied across views",
    ]),
  },
  {
    title: "Release v1.0 (World Class)",
    description: b([
      "Goal: reliability, performance, security hardening, and packaging so Cortex is 'set and forget'.",
      "",
      "Examples:",
      "- SSE reconnection + backpressure + heartbeat semantics",
      "- DB retention/vacuum/index tuning",
      "- Safe workspace sandboxing and markdown rendering",
      "- Docker + deployment docs",
      "- Cortex self-observability",
    ]),
  },
];

export const issues = [
  // ───────────────────────────────────────────────────────────────────────────
  // Existing epics (#1-#6): upgrade from one-liners to real specs.
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cortex-0001",
    existingNumber: 1,
    title: "Cortex MVP: Agent status dashboard",
    milestone: "Release v0.2 (Health + Agents)",
    labels: ["epic", "enhancement", "P0", "area:client", "component:health"],
    body: b([
      "Backlog-Id: cortex-0001",
      "",
      "## Why",
      "Operators need a single screen that answers: Which agents are alive, how stale are they, and where do I click next to diagnose problems.",
      "",
      "This should become the default landing experience (either the Overview page itself or a primary panel on Overview).",
      "",
      "## Scope",
      "- Show all agents (target: 7 agents initially; do not hardcode if avoidable).",
      "- For each agent show:",
      "  - Online/offline state",
      "  - Last heartbeat time (and age)",
      "  - Session count (and recent session update time if available)",
      "  - A compact status indicator (ok/warn/error) suitable for scanning",
      "- Allow basic sorting (status first, then staleness).",
      "- Provide an obvious drill-down to Logs/Errors filtered to the agent where possible.",
      "",
      "## Data Contract",
      "- Primary input: GET /api/health (GatewayHealth) and/or SSE event type \"health\".",
      "- Optional enrichment: GET /api/sessions.",
      "",
      "## Acceptance Criteria",
      "- With healthy data, the dashboard renders within 1s and updates at least every 10s (poll or SSE).",
      "- If /api/health is unavailable, page renders a clear error state and does not crash.",
      "- Stale heartbeat is clearly distinguishable from totally missing data.",
      "- Clicking an agent can navigate to Logs with agent filter applied (or an equivalent workflow).",
      "",
      "## Non-goals",
      "- Alerts/notifications (later, v1.0).",
      "",
      "## Notes",
      "- Shared UI primitives: src/client/components/StatusBadge.tsx exists.",
      "- Health collection is currently stubbed: src/server/collectors/health.ts:5.",
    ]),
  },
  {
    id: "cortex-0002",
    existingNumber: 2,
    title: "Cortex MVP: Sprite fleet status view",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["epic", "enhancement", "P0", "area:client", "component:sprites"],
    body: b([
      "Backlog-Id: cortex-0002",
      "",
      "## Why",
      "Sprites are the highest-churn operational surface; operators need a fleet view to spot stuck, dead, stale, or runaway work quickly.",
      "",
      "## Scope",
      "- Fleet table/grid showing all sprites with:",
      "  - Status: running/dead/complete/stale (exact semantics defined in a dedicated spec task)",
      "  - Assigned task (human-readable summary)",
      "  - Runtime duration and/or startedAt/updatedAt",
      "  - Last log/error indicator (link to Errors filtered to sprite)",
      "- Sorting and filtering by status.",
      "",
      "## Acceptance Criteria",
      "- With mock data, UI renders a useful at-a-glance view on desktop and remains readable on narrow screens.",
      "- Status classification is deterministic and tested (unit tests for classification rules).",
      "",
      "## Dependencies",
      "- Requires a server-side sprite data source and API (likely /api/sprites) to be implemented.",
      "",
      "## Non-goals",
      "- Editing/controlling sprites (start/stop) in v0.3.",
    ]),
  },
  {
    id: "cortex-0003",
    existingNumber: 3,
    title: "Cortex MVP: Cron job viewer",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["epic", "enhancement", "P1", "area:client", "component:crons"],
    body: b([
      "Backlog-Id: cortex-0003",
      "",
      "## Why",
      "Cron jobs are easy to forget until they break. Operators need visibility into schedule and last/next run and failures.",
      "",
      "## Scope",
      "- List all cron jobs with:",
      "  - Name, agentId",
      "  - Enabled/disabled",
      "  - Schedule (expr or everyMs)",
      "  - State: lastStatus, lastRunAt, lastDuration, nextRunAt, runningAt",
      "- Filtering by agentId and status.",
      "",
      "## Data Contract",
      "- GET /api/crons returns CronJob[] (src/shared/types.ts).",
      "- Optional: SSE event type \"crons\" pushes refreshes.",
      "",
      "## Acceptance Criteria",
      "- View renders empty state when no jobs exist.",
      "- Time fields are shown in a readable way (relative + absolute on hover is ideal).",
      "",
      "## Notes",
      "- Collector stub: src/server/collectors/cron.ts:5.",
    ]),
  },
  {
    id: "cortex-0004",
    existingNumber: 4,
    title: "Cortex MVP: Workspace file browser",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["epic", "enhancement", "P1", "area:client", "component:workspace"],
    body: b([
      "Backlog-Id: cortex-0004",
      "",
      "## Why",
      "When diagnosing agent/sprite behavior, operators often need to read the current workspace notes, task markdown, and run artifacts.",
      "",
      "## Scope",
      "- UI to browse a curated subset of workspace files (start with markdown and text).",
      "- Allow selecting an agent/sprite workspace and then file navigation within it.",
      "- File viewer with basic formatting (markdown render preferred) and safe handling for large files.",
      "",
      "## Security Constraints",
      "- MUST prevent arbitrary path traversal; only allow reads under whitelisted roots.",
      "- Do not execute or render raw HTML from markdown by default.",
      "",
      "## Acceptance Criteria",
      "- Attempting to request a file outside allowed roots is rejected server-side.",
      "- Rendering a 1MB markdown file does not freeze the UI.",
      "",
      "## Notes",
      "- This requires API work (list/read endpoints) in addition to UI.",
    ]),
  },
  {
    id: "cortex-0005",
    existingNumber: 5,
    title: "Cortex MVP: Error log viewer",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["epic", "enhancement", "P1", "area:client", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0005",
      "",
      "## Why",
      "Errors are where operators spend time. A fast error view reduces MTTR by making failures searchable and scannable.",
      "",
      "## Scope",
      "- Show error-level logs across supported sources:",
      "  - ~/.openclaw/logs/gateway.err.log",
      "  - ~/.openclaw/logs/gateway.log (error-like lines)",
      "  - /tmp/openclaw/openclaw-YYYY-MM-DD.log (JSON logs that indicate failures/tool errors)",
      "- Search by text and filter by source and time range.",
      "- Clicking an error reveals the raw line and metadata (when available).",
      "",
      "## Data Contract",
      "- GET /api/errors: PaginatedResponse<LogEntry> (same shape as /api/logs but pre-filtered to error).",
      "- Optional: SSE event type \"log_entry\" or \"error\" for real-time arrival.",
      "",
      "## Acceptance Criteria",
      "- Can find a known error string in < 1s over 10k entries (FTS-backed).",
      "- UI supports pagination and does not try to render 10k DOM rows at once.",
      "",
      "## Notes",
      "- This epic depends on implementing: parsers, log-store, /api/errors, and Errors view.",
    ]),
  },
  {
    id: "cortex-0006",
    existingNumber: 6,
    title: "Cortex MVP: Search/sort/filter",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["epic", "enhancement", "P1", "area:client", "component:search"],
    body: b([
      "Backlog-Id: cortex-0006",
      "",
      "## Why",
      "A dashboard without strong search and filtering becomes noise. Operators need fast, consistent interactions across all views.",
      "",
      "## Scope (phased)",
      "- Phase 1 (v0.1): search/filter in Logs and Errors views.",
      "- Phase 2 (v0.3): generalized primitives applied across Sessions/Crons/Models/Sprites/Workspace views.",
      "",
      "## UX Requirements",
      "- URL-synced query params (copy/paste links work).",
      "- Column sorting, per-column filtering where relevant.",
      "- Sensible defaults and quick reset of filters.",
      "",
      "## Acceptance Criteria",
      "- Given a URL with query params, the view rehydrates correctly on refresh.",
      "- Table controls are consistent across views (same look and interactions).",
      "",
      "## Notes",
      "- src/client/components/DataTable.tsx is currently a stub (src/client/components/DataTable.tsx:5).",
    ]),
  },

  // New epics to make the v2 intent explicit.
  {
    id: "cortex-0007",
    title: "Cortex MVP: Log viewer (FTS + filters + time range)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["epic", "enhancement", "P0", "area:client", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0007",
      "",
      "## Why",
      "Logs are the primary debugging surface. A usable log viewer is the fastest way to ship immediate value.",
      "",
      "## Scope",
      "- Logs view that supports:",
      "  - Full-text search (FTS-backed server query)",
      "  - Filter by level and source",
      "  - Time range filter (from/to)",
      "  - Pagination",
      "  - Export current result set (JSON first; CSV optional)",
      "- Display metadata and raw line on demand (details drawer/panel).",
      "",
      "## Data Contract",
      "- GET /api/logs: PaginatedResponse<LogEntry> (src/shared/types.ts).",
      "",
      "## Acceptance Criteria",
      "- With 10k log entries, search and paging remains responsive.",
      "- A log row clearly shows timestamp, level, subsystem/source, and message.",
      "",
      "## Notes",
      "- Backend is currently placeholder: src/server/index.ts:18-24.",
      "- Log-store + parsers are currently stubs: src/server/services/log-store.ts:7, src/server/parsers/*.ts.",
    ]),
  },
  {
    id: "cortex-0008",
    title: "Cortex MVP: Real-time updates via SSE",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["epic", "enhancement", "P1", "area:server", "area:client", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0008",
      "",
      "## Why",
      "The dashboard should feel live: new errors should appear without reload, and health changes should be immediate.",
      "",
      "## Scope",
      "- Server: implement SSE endpoint that streams events to connected clients.",
      "- Client: maintain a single EventSource connection and expose connection state via context.",
      "- At minimum, stream these event types:",
      "  - connected",
      "  - log_entry (new log lines ingested)",
      "  - health (when implemented in v0.2)",
      "",
      "## Acceptance Criteria",
      "- Browser reconnects after server restart without manual reload.",
      "- Client shows a clear connected/disconnected indicator.",
      "",
      "## Notes",
      "- Event bus exists: src/server/services/event-bus.ts.",
      "- SSE route is stubbed: src/server/routes/sse.ts:10.",
      "- Client provider is stubbed: src/client/components/SSEProvider.tsx:7.",
    ]),
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Release v0.1 (Logs + Errors): foundations + end-to-end slice.
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cortex-0010",
    title: "CI: Align workflows with branch rename (main -> master)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:ci"],
    body: b([
      "Backlog-Id: cortex-0010",
      "",
      "## Context",
      "Local branch has been renamed to master, but CI still triggers only on main:",
      "- .github/workflows/ci.yml:4-7",
      "",
      "If the remote default branch is changed to master, CI will stop running unless updated.",
      "",
      "## Scope",
      "- Update CI workflow branch filters to run on master (and optionally keep main during transition).",
      "- Update any documentation that references main as the default branch.",
      "",
      "## Acceptance Criteria",
      "- Pushes and PRs targeting master trigger CI jobs (typecheck/lint/test/build).",
      "- If main still exists temporarily, behavior is documented and intentional.",
      "",
      "## Non-goals",
      "- Repo-level default branch change in GitHub settings (manual action).",
    ]),
  },
  {
    id: "cortex-0011",
    title: "DB: Make `pnpm db:migrate` actually run migrations (currently no-op)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["bug", "P0", "area:db"],
    body: b([
      "Backlog-Id: cortex-0011",
      "",
      "## Context",
      "The repo advertises a migration command:",
      "- package.json:27 runs `tsx src/server/db.ts --migrate`",
      "",
      "But src/server/db.ts does not implement a CLI handler, so running the command produces no DB file and applies no migrations.",
      "",
      "## Scope",
      "- Implement a CLI entrypoint (either inside src/server/db.ts or a dedicated file) that:",
      "  - Resolves DB path (CORTEX_DB_PATH or config default).",
      "  - Creates the parent directory if missing (e.g., ~/.cortex/).",
      "  - Calls initDb + runMigrations using migrations/.",
      "- Make the command idempotent (second run should apply nothing).",
      "",
      "## Acceptance Criteria",
      "- `pnpm db:migrate` creates a DB file and a `migrations` table exists.",
      "- `migrations/001_initial.sql` is applied exactly once.",
      "- Works on macOS/Linux with Node >= 22.",
      "",
      "## Test Plan",
      "- Add a unit test that runs migrations against a temp db path and asserts expected tables exist.",
    ]),
  },
  {
    id: "cortex-0012",
    title: "Server: Initialize DB + run migrations on startup; close DB on shutdown",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:server", "area:db"],
    body: b([
      "Backlog-Id: cortex-0012",
      "",
      "## Context",
      "The server does not currently initialize SQLite or run migrations; it only exposes placeholder endpoints:",
      "- src/server/index.ts:15-24",
      "",
      "DB helpers and schema exist:",
      "- src/server/db.ts",
      "- migrations/001_initial.sql",
      "",
      "## Scope",
      "- On server startup:",
      "  - Ensure DB directory exists.",
      "  - initDb(config.dbPath) and runMigrations(db, migrationsDir).",
      "- On server shutdown (SIGINT/SIGTERM):",
      "  - stop tailers/collectors (when implemented)",
      "  - closeDb()",
      "",
      "## Acceptance Criteria",
      "- Starting the server on a fresh machine creates the DB and tables automatically.",
      "- SIGINT shuts down cleanly without leaving the process hanging (no zombie watchers).",
      "",
      "## Notes",
      "- This issue should also remove the placeholder routes in src/server/index.ts and mount real routers once implemented.",
    ]),
  },
  {
    id: "cortex-0013",
    title: "Server: Serve built client assets in production (`pnpm start` runs one process)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:server"],
    body: b([
      "Backlog-Id: cortex-0013",
      "",
      "## Context",
      "In dev, Vite serves the client and proxies /api to the server. In production, `pnpm start` only runs the server:",
      "- package.json:17",
      "",
      "But the server does not currently serve dist/client, so production UX is undefined.",
      "",
      "## Scope",
      "- Serve static files from dist/client when NODE_ENV=production (or always when dist/client exists).",
      "- SPA fallback: unknown routes should return dist/client/index.html.",
      "- Keep /api/* routes working as before.",
      "",
      "## Acceptance Criteria",
      "- After `pnpm build && pnpm start`, opening http://localhost:18790/ loads the React app.",
      "- Refreshing a deep route (e.g., /logs) works (SPA fallback).",
      "",
      "## Non-goals",
      "- Auth, TLS, reverse proxy configuration.",
    ]),
  },
  {
    id: "cortex-0014",
    title: "API: Implement GET /api/logs and GET /api/errors (LogQuery + pagination + validation)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:server", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0014",
      "",
      "## Context",
      "API endpoints are currently placeholders:",
      "- src/server/index.ts:18-23",
      "- src/server/routes/api.ts:10-15",
      "",
      "The shared query type already exists:",
      "- src/shared/types.ts:94 (LogQuery)",
      "",
      "## Scope",
      "- Implement:",
      "  - GET /api/logs",
      "  - GET /api/errors (equivalent to /api/logs with level=error unless explicitly overridden)",
      "- Parse and validate query params:",
      "  - q, level, source, from, to, sort, order, page, limit",
      "- Return PaginatedResponse<LogEntry> with stable ordering.",
      "",
      "## Acceptance Criteria",
      "- Invalid query params return HTTP 400 with actionable error message.",
      "- Pagination is correct (hasMore toggles accurately).",
      "- Sorting is deterministic for equal timestamps (tie-break by id).",
      "",
      "## Notes",
      "- Backing implementation should use src/server/services/log-store.ts once implemented.",
    ]),
  },
  {
    id: "cortex-0015",
    title: "Logs: Implement parsers for all 3 sources + real unit tests",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:server", "component:logs", "area:testing"],
    body: b([
      "Backlog-Id: cortex-0015",
      "",
      "## Context",
      "Parsers are stubs returning null:",
      "- src/server/parsers/json-log.ts:14",
      "- src/server/parsers/gateway-log.ts:12",
      "- src/server/parsers/gateway-err.ts:12",
      "",
      "Existing unit tests currently only assert null placeholder behavior:",
      "- tests/unit/parsers/*.test.ts",
      "",
      "## Scope",
      "- Implement parsing logic per file header docs:",
      "  - json-log: support wrapper format and raw numbered args format",
      "  - gateway-log: parse \"<iso> [subsystem] message\" and infer level",
      "  - gateway-err: parse \"<iso> error message\" as error-level",
      "- Update tests to cover:",
      "  - happy paths",
      "  - malformed lines",
      "  - level inference edge cases",
      "",
      "## Acceptance Criteria",
      "- Parsers produce ParsedLogEntry with correct ts and fields.",
      "- Test suite includes representative sample lines for each source.",
      "",
      "## Non-goals",
      "- Perfect coverage of every possible log variant; focus on OpenClaw formats described in CLAUDE.md.",
    ]),
  },
  {
    id: "cortex-0016",
    title: "Logs: Implement log-store insert/query (SQLite + FTS5) + real unit tests",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:db", "component:logs", "area:testing"],
    body: b([
      "Backlog-Id: cortex-0016",
      "",
      "## Context",
      "SQLite schema exists (with FTS5) but the log-store is stubbed:",
      "- migrations/001_initial.sql",
      "- src/server/services/log-store.ts:7-18",
      "",
      "Current tests only assert empty placeholder behavior:",
      "- tests/unit/services/log-store.test.ts:5",
      "",
      "## Scope",
      "- Implement insertLogEntry(entry):",
      "  - Insert into log_entries",
      "  - Serialize metadata to JSON (or NULL)",
      "  - Enforce maxLogEntries retention (config.maxLogEntries) in a safe, bounded way",
      "- Implement queryLogs(query):",
      "  - Full-text search via log_entries_fts when q provided",
      "  - Filters: level, source, from, to",
      "  - Sorting: timestamp (default) and optional level",
      "  - Pagination: page/limit and hasMore",
      "",
      "## Acceptance Criteria",
      "- queryLogs({ q: \"foo\" }) uses FTS and returns matching rows.",
      "- queryLogs supports combining q + filters + time range.",
      "- Retention deletes oldest rows and keeps FTS consistent (triggers handle this).",
      "",
      "## Test Plan",
      "- Use a temp DB file per test; run migrations; assert insert/query results.",
    ]),
  },
  {
    id: "cortex-0017",
    title: "Logs: Implement log tailer to ingest all sources (rotation-safe) and broadcast new entries",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:server", "component:logs", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0017",
      "",
      "## Context",
      "Log tailer is stubbed:",
      "- src/server/services/log-tailer.ts:5-11",
      "",
      "Data sources are documented in CLAUDE.md:",
      "- /tmp/openclaw/openclaw-YYYY-MM-DD.log",
      "- ~/.openclaw/logs/gateway.log",
      "- ~/.openclaw/logs/gateway.err.log",
      "",
      "## Scope",
      "- Implement startLogTailer()/stopLogTailer() to:",
      "  - Tail all sources (start at EOF; do not re-ingest old logs by default)",
      "  - Parse each new line and insert via log-store",
      "  - Broadcast SSE events (log_entry) after successful insert",
      "- Handle log rotation/truncation:",
      "  - When file size shrinks, reset cursor to start or EOF (pick one and document)",
      "  - When date changes, start tailing the new JSON log file",
      "",
      "## Acceptance Criteria",
      "- Given an appended line, it appears in DB and is emitted to SSE listeners within 1s.",
      "- Tailer can be started/stopped repeatedly without leaking timers/watchers.",
      "",
      "## Non-goals",
      "- Exactly-once ingestion across restarts (later enhancement).",
    ]),
  },
  {
    id: "cortex-0018",
    title: "SSE: Implement /api/events stream (connected + heartbeat + log_entry events)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:server", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0018",
      "",
      "## Context",
      "SSE route is stubbed:",
      "- src/server/routes/sse.ts:10",
      "",
      "Event bus exists:",
      "- src/server/services/event-bus.ts",
      "",
      "## Scope",
      "- Implement GET /api/events as an SSE endpoint:",
      "  - On connect: emit a \"connected\" event (include server timestamp)",
      "  - Keep-alive heartbeat comment/event every ~15s to prevent idle timeouts",
      "  - Subscribe to event-bus and forward events to the client",
      "  - Unsubscribe on disconnect",
      "",
      "## Acceptance Criteria",
      "- A browser EventSource can stay connected for 5+ minutes without dropping (local dev).",
      "- Disconnect cleans up listener (no memory leak / growing listener set).",
      "",
      "## Notes",
      "- Event types are defined in src/shared/types.ts (SSEEventType).",
    ]),
  },
  {
    id: "cortex-0019",
    title: "Client: Implement Logs view (search/filter/time range/pagination/export) backed by /api/logs",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:client", "component:logs", "component:search"],
    body: b([
      "Backlog-Id: cortex-0019",
      "",
      "## Context",
      "Logs view is currently a placeholder:",
      "- src/client/views/Logs.tsx:5-11",
      "",
      "## Scope",
      "- Build a usable Logs page that:",
      "  - Fetches /api/logs with query params",
      "  - Provides controls: q, level, source, from/to, page/limit",
      "  - Displays results in a table with at least: timestamp, level, source, message",
      "  - Allows expanding a row to see metadata and raw line",
      "  - Exports current results (JSON is sufficient for v0.1)",
      "",
      "## Acceptance Criteria",
      "- Interactions do not block the UI; query changes are debounced (or require explicit submit).",
      "- Empty state and error state are clear and actionable.",
      "",
      "## Notes",
      "- useApi exists but uses a polling model; it may be replaced with request-on-change for this view.",
      "- DataTable is currently a stub; this view can start with a dedicated table and later refactor.",
    ]),
  },
  {
    id: "cortex-0020",
    title: "Client: Implement Errors view backed by /api/errors (filter/search/pagination + details)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P0", "area:client", "component:logs", "component:search"],
    body: b([
      "Backlog-Id: cortex-0020",
      "",
      "## Context",
      "Errors view is currently a placeholder:",
      "- src/client/views/Errors.tsx:5-11",
      "",
      "## Scope",
      "- Build an Errors page that:",
      "  - Calls /api/errors (or /api/logs with level=error) with pagination",
      "  - Offers search + source + time range filters",
      "  - Shows raw line + metadata on selection",
      "  - Encourages a workflow to jump to full logs around the error timestamp",
      "",
      "## Acceptance Criteria",
      "- User can quickly answer: what broke, when, and in which subsystem/source.",
      "- Clicking \"view surrounding logs\" (or equivalent) opens Logs with from/to around the error.",
    ]),
  },
  {
    id: "cortex-0021",
    title: "Client: Implement DataTable v1 (sorting + pagination) and adopt it in Logs/Errors",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:client", "component:search"],
    body: b([
      "Backlog-Id: cortex-0021",
      "",
      "## Context",
      "DataTable is currently a stub:",
      "- src/client/components/DataTable.tsx:5-7",
      "",
      "## Scope",
      "- Implement a reusable DataTable component that supports:",
      "  - Column definitions (header, accessor, optional render)",
      "  - Client-side sorting UI (even if sorting is implemented server-side)",
      "  - Pagination controls",
      "  - Row click to open details panel (optional API)",
      "- Refactor Logs and Errors views to use DataTable.",
      "",
      "## Acceptance Criteria",
      "- DataTable can render 100 rows without visible jank.",
      "- Sorting and paging are accessible (keyboard focus, clear affordances).",
    ]),
  },
  {
    id: "cortex-0022",
    title: "Client: Implement SearchBar v1 (controlled + debounced) and integrate into Logs/Errors",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:client", "component:search"],
    body: b([
      "Backlog-Id: cortex-0022",
      "",
      "## Context",
      "SearchBar exists but is an uncontrolled input:",
      "- src/client/components/SearchBar.tsx:5-7",
      "",
      "## Scope",
      "- Make SearchBar controlled and reusable:",
      "  - value, onChange",
      "  - optional debounce (or provide a useDebounce hook)",
      "  - clear button",
      "- Use it in Logs and Errors views.",
      "",
      "## Acceptance Criteria",
      "- Typing does not issue a network request per keystroke (debounce or explicit submit).",
      "- Hitting Escape clears the query (or explicit clear button exists).",
    ]),
  },
  {
    id: "cortex-0023",
    title: "Client: Implement ExportButton (JSON + CSV optional) and wire to Logs/Errors datasets",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:client", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0023",
      "",
      "## Context",
      "ExportButton is stubbed:",
      "- src/client/components/ExportButton.tsx:5-7",
      "",
      "A usable export helper exists:",
      "- src/client/hooks/useExport.ts",
      "",
      "## Scope",
      "- Implement ExportButton UI to:",
      "  - Export currently visible page as JSON",
      "  - (Optional) export as CSV if easy",
      "  - Copy JSON to clipboard",
      "- Integrate it into Logs and Errors views.",
      "",
      "## Acceptance Criteria",
      "- Exported JSON matches the LogEntry shape including metadata when present.",
      "- Export does not block the UI thread noticeably for typical page sizes (<= 500 rows).",
    ]),
  },
  {
    id: "cortex-0024",
    title: "Client: Implement SSEProvider (EventSource + reconnect) and expose connection state",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:client", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0024",
      "",
      "## Context",
      "SSEProvider is a stub that always returns connected: false:",
      "- src/client/components/SSEProvider.tsx:7-10",
      "",
      "## Scope",
      "- Connect to /api/events using EventSource.",
      "- Maintain connection state:",
      "  - connected true/false",
      "  - lastEventAt timestamp (optional but useful)",
      "- Implement reconnection strategy:",
      "  - EventSource reconnects automatically, but surface status + error handling",
      "- Parse incoming messages as SSEEvent (src/shared/types.ts) and expose a subscription mechanism or lastEvent.",
      "",
      "## Acceptance Criteria",
      "- Restarting the server causes the client to reconnect within 10s and update connected state accordingly.",
      "- Invalid/malformed events do not crash the app (log and continue).",
    ]),
  },
  {
    id: "cortex-0025",
    title: "Client: Wire SSE log_entry events into Logs/Errors UX (auto-refresh or live append)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P2", "area:client", "component:sse", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0025",
      "",
      "## Context",
      "Once SSE is connected, new log entries can be pushed to the browser; today views are polling-only.",
      "",
      "## Scope",
      "- On receiving SSE log_entry events:",
      "  - If the user is on page 1 and sorted newest-first, append to the table (or trigger a refresh).",
      "  - If the user has filters active, only surface matching events (or simply refresh with the current query).",
      "- Show a small \"new events\" indicator when auto-append is not safe (e.g., user is paged deep).",
      "",
      "## Acceptance Criteria",
      "- With live ingestion, errors appear without manual reload.",
      "- UX does not reorder the table unexpectedly while the user is reading older pages.",
    ]),
  },
  {
    id: "cortex-0026",
    title: "Testing: Replace placeholder unit tests with real behavior for v0.1 logs pipeline",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:testing", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0026",
      "",
      "## Context",
      "Many tests currently assert placeholder behavior (e.g., parsers return null):",
      "- tests/unit/parsers/*.test.ts",
      "- tests/unit/services/log-store.test.ts",
      "- tests/unit/routes/api.test.ts",
      "",
      "## Scope",
      "- Update unit tests to validate real behavior for:",
      "  - parsers (json/gateway/gateway-err)",
      "  - log-store insert/query",
      "  - /api/logs and /api/errors route behavior (including validation)",
      "- Introduce fixtures for representative log lines.",
      "",
      "## Acceptance Criteria",
      "- Tests fail if parsers regress on known formats.",
      "- log-store tests exercise FTS queries, not just filters.",
      "",
      "## Notes",
      "- Consider using a temp DB per test and running migrations programmatically.",
    ]),
  },
  {
    id: "cortex-0027",
    title: "E2E: Replace placeholder Playwright tests with Logs/Errors flows (search/filter/export)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:testing", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0027",
      "",
      "## Context",
      "Playwright specs are currently placeholders:",
      "- tests/e2e/*.spec.ts",
      "",
      "## Scope",
      "- Implement E2E tests that validate the actual user workflow:",
      "  - Logs page loads and displays rows (use mock API or seeded DB)",
      "  - Search narrows results",
      "  - Filter by level/source",
      "  - Export produces a downloadable file (or verify clipboard for copy)",
      "  - Errors page loads and supports the same interactions",
      "",
      "## Acceptance Criteria",
      "- Tests run reliably locally and in CI without depending on a running OpenClaw instance.",
      "",
      "## Notes",
      "- Consider adding a server \"mock mode\" for deterministic fixtures in tests.",
    ]),
  },
  {
    id: "cortex-0028",
    title: "CI: Add Playwright E2E job (or explicitly disable the e2e gate)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:ci", "area:testing"],
    body: b([
      "Backlog-Id: cortex-0028",
      "",
      "## Context",
      "CI currently runs typecheck/lint/unit-tests/build but not Playwright E2E.",
      "- .github/workflows/ci.yml",
      "",
      "quality-gates-config.yml indicates e2e-tests should be enforced, but there is no implementation wiring.",
      "",
      "## Scope",
      "- Option A (recommended): Add a CI job that runs `pnpm test:e2e` with Playwright deps installed.",
      "- Option B: If we do not want E2E in CI yet, update docs/config to make that explicit.",
      "",
      "## Acceptance Criteria",
      "- CI clearly communicates whether E2E is a required gate.",
      "- If enabled, E2E job is stable (retries ok) and artifacts (HTML report) are available.",
    ]),
  },
  {
    id: "cortex-0029",
    title: "Quality: Enforce meaningful coverage thresholds (ramp toward targets in quality-gates-config.yml)",
    milestone: "Release v0.1 (Logs + Errors)",
    labels: ["enhancement", "P1", "area:testing"],
    body: b([
      "Backlog-Id: cortex-0029",
      "",
      "## Context",
      "Vitest coverage thresholds are currently set to 0, so coverage is not a real gate:",
      "- vitest.config.ts:31-39",
      "",
      "Yet quality-gates-config.yml defines ambitious targets (parsers 95%+, etc.).",
      "",
      "## Scope",
      "- Set non-zero thresholds that match reality for v0.1.",
      "- Establish a ratchet plan to reach the targets (e.g., per-folder thresholds or gradual increases).",
      "",
      "## Acceptance Criteria",
      "- CI fails when new code significantly reduces coverage in parsers/services/routes.",
      "- The thresholds are documented (why these numbers, how to raise).",
    ]),
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Release v0.2 (Health + Agents)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cortex-0030",
    title: "OpenClaw integration: implement CLI runner (timeouts, JSON parsing, structured errors)",
    milestone: "Release v0.2 (Health + Agents)",
    labels: ["enhancement", "P0", "area:server", "component:health"],
    body: b([
      "Backlog-Id: cortex-0030",
      "",
      "## Context",
      "Collectors intend to call OpenClaw commands (see CLAUDE.md:58), but no implementation exists.",
      "",
      "## Scope",
      "- Implement a small service for calling OpenClaw CLI commands safely:",
      "  - Configurable binary name/path (default: `openclaw` on PATH)",
      "  - Timeouts (fail fast; no hung processes)",
      "  - Capture stdout/stderr",
      "  - Parse JSON outputs when applicable",
      "  - Return structured errors (exit code, stderr snippet, command)",
      "",
      "## Acceptance Criteria",
      "- A failing command returns a typed error with actionable debug context.",
      "- A hung command is killed after timeout and reported as timeout.",
      "",
      "## Notes",
      "- This should be easy to mock in unit tests (inject a runner interface).",
    ]),
  },
  {
    id: "cortex-0031",
    title: "Health: implement collectHealth + /api/health endpoint + SSE health events",
    milestone: "Release v0.2 (Health + Agents)",
    labels: ["enhancement", "P0", "area:server", "component:health", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0031",
      "",
      "## Context",
      "Health collector is stubbed:",
      "- src/server/collectors/health.ts:5",
      "",
      "Shared type exists:",
      "- src/shared/types.ts:66 (GatewayHealth)",
      "",
      "## Scope",
      "- Implement collectHealth() to poll gateway health on an interval (config.pollIntervalFast).",
      "  - Preferred: call OpenClaw (e.g., `openclaw gateway call health`) and parse JSON",
      "  - Alternative: call gateway HTTP on config.gatewayPort if that is the actual interface",
      "- Store last known health in memory (and optionally DB snapshots later).",
      "- Implement GET /api/health returning the latest snapshot + timestamp.",
      "- Broadcast SSE event type \"health\" when health changes (or on every poll initially).",
      "",
      "## Acceptance Criteria",
      "- /api/health returns GatewayHealth-compatible JSON.",
      "- If collector errors, last good state remains available with an error indicator.",
      "- SSE clients receive health updates without polling.",
    ]),
  },
  {
    id: "cortex-0032",
    title: "Client: Overview page health summary (status badges + last updated)",
    milestone: "Release v0.2 (Health + Agents)",
    labels: ["enhancement", "P0", "area:client", "component:health"],
    body: b([
      "Backlog-Id: cortex-0032",
      "",
      "## Context",
      "Overview is currently a placeholder:",
      "- src/client/views/Overview.tsx:5-11",
      "",
      "## Scope",
      "- Show a compact health summary on Overview:",
      "  - Gateway ok flag",
      "  - Channel health summary (count ok/warn/error if available)",
      "  - Agent counts (online/offline/stale)",
      "  - Last updated time and refresh indicator",
      "- Source data from /api/health (poll or SSE).",
      "",
      "## Acceptance Criteria",
      "- With no data, show an empty state that suggests starting OpenClaw/gateway.",
      "- With data, statuses are easy to scan in < 5 seconds.",
    ]),
  },
  {
    id: "cortex-0033",
    title: "Client: Implement Agent status dashboard UI (fulfills epic #1)",
    milestone: "Release v0.2 (Health + Agents)",
    labels: ["enhancement", "P0", "area:client", "component:health"],
    body: b([
      "Backlog-Id: cortex-0033",
      "",
      "## Context",
      "Epic #1 defines the operator UX; this issue is the concrete implementation work once /api/health exists.",
      "",
      "## Scope",
      "- Build the agent list/table UI:",
      "  - Status badge (ok/warn/error/offline)",
      "  - Heartbeat age (relative time)",
      "  - Session count and recency",
      "  - Drill-down links (Logs/Errors filtered by agent)",
      "- Ensure responsive layout and no horizontal scroll for typical content.",
      "",
      "## Acceptance Criteria",
      "- Meets epic #1 acceptance criteria.",
      "- Visual status mapping is consistent with StatusBadge component.",
    ]),
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Release v0.3 (Ops Views)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cortex-0040",
    title: "Sessions: implement collectSessions (read sessions.json) + GET /api/sessions",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P0", "area:server", "component:sessions"],
    body: b([
      "Backlog-Id: cortex-0040",
      "",
      "## Context",
      "Sessions collector is stubbed:",
      "- src/server/collectors/sessions.ts:5",
      "",
      "Data source is documented:",
      "- CLAUDE.md:63 (~/.openclaw/agents/*/sessions/sessions.json)",
      "",
      "Shared type exists:",
      "- src/shared/types.ts:38 (Session)",
      "",
      "## Scope",
      "- Read and parse sessions.json files from configured OPENCLAW_HOME.",
      "- Compute derived fields (usagePercent, ageMs) consistently.",
      "- Store the latest sessions in memory.",
      "- Implement GET /api/sessions returning Session[] (sorted by staleness or usage).",
      "",
      "## Acceptance Criteria",
      "- Missing files are handled gracefully (empty list + diagnostic).",
      "- Parsing is robust to partial/invalid JSON (skip bad files, continue).",
    ]),
  },
  {
    id: "cortex-0041",
    title: "Client: Implement Sessions view (token usage + search/sort)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P0", "area:client", "component:sessions", "component:search"],
    body: b([
      "Backlog-Id: cortex-0041",
      "",
      "## Context",
      "Sessions view is currently a placeholder:",
      "- src/client/views/Sessions.tsx:5-11",
      "",
      "## Scope",
      "- Render sessions in a table showing:",
      "  - agentId, model",
      "  - totalTokens, contextTokens, usagePercent",
      "  - updatedAt (relative) and age",
      "- Provide search (agentId/model) and sorting (usage, staleness).",
      "",
      "## Acceptance Criteria",
      "- High usage sessions (>= 80%) are visually highlighted (usageColor helper exists).",
      "- Empty state is helpful and explains where sessions.json is read from.",
    ]),
  },
  {
    id: "cortex-0042",
    title: "Crons: implement collectCrons + GET /api/crons",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:server", "component:crons"],
    body: b([
      "Backlog-Id: cortex-0042",
      "",
      "## Context",
      "Cron collector is stubbed:",
      "- src/server/collectors/cron.ts:5",
      "",
      "Shared type exists:",
      "- src/shared/types.ts:49 (CronJob)",
      "",
      "## Scope",
      "- Implement collectCrons() using the OpenClaw CLI runner (from v0.2):",
      "  - call `openclaw cron list` (or the correct command; verify against OpenClaw)",
      "  - parse JSON into CronJob[]",
      "- Store in memory and expose via GET /api/crons.",
      "",
      "## Acceptance Criteria",
      "- If the CLI command is unavailable, /api/crons returns a clear error message and HTTP 503.",
    ]),
  },
  {
    id: "cortex-0043",
    title: "Client: Implement Cron Jobs view (schedule + last/next run + status)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:client", "component:crons", "component:search"],
    body: b([
      "Backlog-Id: cortex-0043",
      "",
      "## Context",
      "Crons view is currently a placeholder:",
      "- src/client/views/Crons.tsx:5-11",
      "",
      "## Scope",
      "- Render CronJob[] from /api/crons in a table with filters and sorting.",
      "- Provide visual indication for failures and missed schedules (if detectable).",
      "",
      "## Acceptance Criteria",
      "- Renders correctly with 0, 1, and many jobs.",
      "- Time formatting is readable and consistent with other views.",
    ]),
  },
  {
    id: "cortex-0044",
    title: "Models: implement collectModels + GET /api/models",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:server", "component:models"],
    body: b([
      "Backlog-Id: cortex-0044",
      "",
      "## Context",
      "Models collector is stubbed:",
      "- src/server/collectors/models.ts:5",
      "",
      "Shared type exists:",
      "- src/shared/types.ts:77 (ModelStatus)",
      "",
      "## Scope",
      "- Implement collectModels() using the OpenClaw CLI runner:",
      "  - call `openclaw models status` (or correct command)",
      "  - parse JSON into ModelStatus",
      "- Store in memory and expose via GET /api/models.",
      "",
      "## Acceptance Criteria",
      "- /api/models returns the same response shape consistently across polls.",
    ]),
  },
  {
    id: "cortex-0045",
    title: "Client: Implement Models view (default model + allowed/fallbacks + auth providers)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:client", "component:models"],
    body: b([
      "Backlog-Id: cortex-0045",
      "",
      "## Context",
      "Models view is currently a placeholder:",
      "- src/client/views/Models.tsx:5-11",
      "",
      "## Scope",
      "- Render /api/models (ModelStatus) in a readable format:",
      "  - defaultModel, resolvedDefault",
      "  - allowed models list",
      "  - fallbacks list",
      "  - auth providers summary (if present)",
      "",
      "## Acceptance Criteria",
      "- Operators can see misconfiguration quickly (e.g., resolvedDefault missing from allowed).",
    ]),
  },
  {
    id: "cortex-0046",
    title: "Workspace: define allowed roots + implement /api/workspace/files (list + read)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:server", "component:workspace"],
    body: b([
      "Backlog-Id: cortex-0046",
      "",
      "## Context",
      "Epic #4 requires server APIs; no endpoints exist today.",
      "",
      "## Scope",
      "- Define where workspace files live (agent workspaces and/or configured roots).",
      "- Implement endpoints:",
      "  - GET /api/workspace/roots (optional) OR encode root in request params",
      "  - GET /api/workspace/files?root=<id>&path=<relative> to list directory entries",
      "  - GET /api/workspace/file?root=<id>&path=<relative> to read file content",
      "- Security:",
      "  - Enforce root allowlist, reject path traversal, cap file read size.",
      "",
      "## Acceptance Criteria",
      "- Requesting `..` paths is rejected with 400.",
      "- Binary files are detected and rejected or safely handled.",
    ]),
  },
  {
    id: "cortex-0047",
    title: "Client: Implement Workspace browser view (tree + file viewer) (fulfills epic #4)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:client", "component:workspace"],
    body: b([
      "Backlog-Id: cortex-0047",
      "",
      "## Context",
      "Workspace UI does not exist; Layout nav will need a new entry for this view.",
      "",
      "## Scope",
      "- Add a new route (e.g., /workspace) and navigation item.",
      "- Implement a two-pane layout:",
      "  - left: directory tree / file list",
      "  - right: file content viewer",
      "- Integrate with /api/workspace endpoints.",
      "",
      "## Acceptance Criteria",
      "- Switching files is fast (cache last N file contents).",
      "- Large file shows a warning and does not lock the browser.",
    ]),
  },
  {
    id: "cortex-0048",
    title: "Search/sort/filter: URL-synced query state primitives and apply across views (fulfills epic #6)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P1", "area:client", "component:search"],
    body: b([
      "Backlog-Id: cortex-0048",
      "",
      "## Context",
      "Search/filter exists only as ad-hoc placeholders. We need consistent primitives so all views behave the same.",
      "",
      "## Scope",
      "- Implement a small query-state layer:",
      "  - Reads/writes URL query params for q/sort/order/page/limit and view-specific filters",
      "  - Exposes typed helpers/hooks for components to use",
      "- Apply to at least: Logs, Errors, Sessions, Crons views.",
      "",
      "## Acceptance Criteria",
      "- Copy/pasting a URL reproduces the same table state.",
      "- Back/forward navigation works correctly with query changes.",
    ]),
  },
  {
    id: "cortex-0049",
    title: "Sprites: Spec spike - define sprite model, statuses, and data source for fleet view",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P0", "area:docs", "component:sprites"],
    body: b([
      "Backlog-Id: cortex-0049",
      "",
      "## Context",
      "Epic #2 requires a clear, testable definition of:",
      "- What a sprite is (in OpenClaw terms)",
      "- Where sprite state comes from (gateway health? sessions? logs? filesystem?)",
      "- How to classify status (running/dead/complete/stale) deterministically",
      "",
      "## Deliverable",
      "- A written spec (Markdown) that includes:",
      "  - Proposed API shape (Sprite[]), including required fields",
      "  - Status rules with thresholds (stale window, dead detection)",
      "  - Data source(s) and fallback behavior when data is missing",
      "  - Example JSON payloads for at least 5 sprites across statuses",
      "",
      "## Acceptance Criteria",
      "- Another engineer can implement /api/sprites and the UI from this doc without guessing.",
    ]),
  },
  {
    id: "cortex-0050",
    title: "Sprites: Implement server-side sprite collector + GET /api/sprites per spec",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P0", "area:server", "component:sprites"],
    body: b([
      "Backlog-Id: cortex-0050",
      "",
      "## Context",
      "Depends on the sprite spec (cortex-0049).",
      "",
      "## Scope",
      "- Implement a collector that produces the Sprite[] data model at a fixed interval.",
      "- Expose GET /api/sprites.",
      "- Add unit tests for status classification logic.",
      "",
      "## Acceptance Criteria",
      "- /api/sprites returns stable ordering (e.g., running first, then stale, dead, complete).",
      "- Classification behavior is covered by unit tests.",
    ]),
  },
  {
    id: "cortex-0051",
    title: "Client: Implement Sprite fleet status view UI (fulfills epic #2)",
    milestone: "Release v0.3 (Ops Views)",
    labels: ["enhancement", "P0", "area:client", "component:sprites", "component:search"],
    body: b([
      "Backlog-Id: cortex-0051",
      "",
      "## Context",
      "UI work once /api/sprites exists.",
      "",
      "## Scope",
      "- Add a new route/nav item for Sprites (or incorporate into Overview if preferred).",
      "- Render sprite fleet table with filtering/sorting.",
      "- Provide drill-down links to Errors/Logs filtered to sprite when possible.",
      "",
      "## Acceptance Criteria",
      "- Meets epic #2 acceptance criteria.",
      "- Works with 100+ sprites without unusable jank (pagination or virtualization as needed).",
    ]),
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Release v1.0 (World Class) - curated set (not exhaustive).
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cortex-0060",
    title: "Perf: DB retention/vacuum strategy and log query latency budget",
    milestone: "Release v1.0 (World Class)",
    labels: ["enhancement", "P2", "area:db", "component:logs"],
    body: b([
      "Backlog-Id: cortex-0060",
      "",
      "## Why",
      "As log volume grows, query speed and disk usage become the bottleneck.",
      "",
      "## Scope",
      "- Define a latency budget for /api/logs (p50/p95) at 10k, 100k, 1M rows.",
      "- Implement a retention strategy beyond maxLogEntries if needed:",
      "  - time-based retention (e.g., keep last 7d) or size-based",
      "- Add periodic vacuum/analyze scheduling guidelines (and avoid doing it too often).",
      "",
      "## Acceptance Criteria",
      "- Documented retention knobs and safe defaults.",
      "- /api/logs queries remain fast enough for interactive use under target loads.",
    ]),
  },
  {
    id: "cortex-0061",
    title: "Reliability: SSE reconnection semantics + server heartbeats + stale detection",
    milestone: "Release v1.0 (World Class)",
    labels: ["enhancement", "P2", "area:server", "area:client", "component:sse"],
    body: b([
      "Backlog-Id: cortex-0061",
      "",
      "## Why",
      "SSE reliability is critical; operators must trust that 'connected' means real updates are flowing.",
      "",
      "## Scope",
      "- Define heartbeat event semantics (server emits, client tracks lastEventAt).",
      "- Detect 'stale connection' even if EventSource remains open (no events for N seconds).",
      "- Backoff strategy for repeated reconnect failures and clear UI states.",
      "",
      "## Acceptance Criteria",
      "- Client transitions to a 'stale' or 'disconnected' state when no events arrive beyond threshold.",
      "- Clear operator-facing diagnostics (e.g., last event timestamp).",
    ]),
  },
  {
    id: "cortex-0062",
    title: "Security: Workspace sandboxing and safe markdown rendering",
    milestone: "Release v1.0 (World Class)",
    labels: ["enhancement", "P2", "area:server", "area:client", "component:workspace"],
    body: b([
      "Backlog-Id: cortex-0062",
      "",
      "## Why",
      "Workspace browsing is a security boundary: path traversal and unsafe markdown/HTML can become a local attack vector.",
      "",
      "## Scope",
      "- Server:",
      "  - Harden path normalization and allowlist roots",
      "  - File type allowlist (start: .md, .txt, .json, .log)",
      "  - Size limits and streaming reads for large files",
      "- Client:",
      "  - Render markdown without raw HTML execution by default",
      "  - Handle large files with truncation + \"load more\"",
      "",
      "## Acceptance Criteria",
      "- Security tests cover path traversal attempts and large-file behavior.",
    ]),
  },
  {
    id: "cortex-0063",
    title: "Packaging: Dockerfile + compose + deployment docs (single-command local bringup)",
    milestone: "Release v1.0 (World Class)",
    labels: ["enhancement", "P2", "area:docs", "area:ci"],
    body: b([
      "Backlog-Id: cortex-0063",
      "",
      "## Why",
      "If Cortex requires bespoke setup, it will rot. One-command bringup enables adoption and consistent demos.",
      "",
      "## Scope",
      "- Provide a Dockerfile that builds the client + server and runs production mode.",
      "- Provide a docker-compose example that documents required volume mounts for logs and OPENCLAW_HOME.",
      "- Document environment variables and ports in README.",
      "",
      "## Acceptance Criteria",
      "- `docker compose up` yields a working UI at a documented port with mock data or mounted logs.",
    ]),
  },
  {
    id: "cortex-0064",
    title: "Observability: Cortex self-health endpoint and lightweight runtime metrics",
    milestone: "Release v1.0 (World Class)",
    labels: ["enhancement", "P2", "area:server"],
    body: b([
      "Backlog-Id: cortex-0064",
      "",
      "## Why",
      "If Cortex is the observability tool, it must report on itself: tailer lag, DB health, last collector run, etc.",
      "",
      "## Scope",
      "- Add /api/status (or extend /api/ping) to include:",
      "  - DB path, size, migration version",
      "  - Tailer offsets + last ingest time per source",
      "  - Collector lastUpdated timestamps",
      "  - SSE connected client count",
      "",
      "## Acceptance Criteria",
      "- Operators can quickly tell if Cortex is failing to ingest or collect data.",
    ]),
  },
];

